# Generated by Django 3.0.3 on 2020-02-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0002_moviegenre_label'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateTimeField(null=True)),
                ('date_return', models.DateTimeField(null=True)),
                ('fk_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Client')),
                ('fk_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Movies')),
            ],
        ),
    ]
