# Generated by Django 3.0.3 on 2020-02-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviegenre_label'),
        ('shop', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieRent',
            new_name='MoviesRent',
        ),
    ]
