# Generated by Django 3.0.3 on 2020-03-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('location', '0003_auto_20200303_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesrent',
            name='fk_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_rent', to='shop.Client'),
        ),
    ]
