# Generated by Django 3.0.3 on 2020-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('compteur', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
