# Generated by Django 3.0.3 on 2020-03-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_visit_stat_compteur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit_stat',
            unique_together={('url', 'ip', 'date')},
        ),
    ]
