# Generated by Django 3.0.3 on 2020-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
