# Generated by Django 3.0.3 on 2020-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviegenre_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='réalisateur'),
        ),
    ]
