# Generated by Django 3.0.3 on 2020-03-02 14:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movies_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text='The registered model identifier.', max_length=100, verbose_name='identifier')),
                ('object_id', models.IntegerField(db_index=True, help_text='The object ID of this translation', verbose_name='The object ID')),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], db_index=True, default='fr-fr', help_text='The language for this translation', max_length=10, verbose_name='language')),
                ('field_name', models.CharField(db_index=True, help_text='The model field name for this translation.', max_length=100, verbose_name='field name')),
                ('field_value', models.TextField(help_text='The translated content for the field.', null=True, verbose_name='field value')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelManagers(
            name='movies',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='description',
            new_name='description_af',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='description_ar',
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
