# Generated by Django 3.0.3 on 2020-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200303_0829'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movies',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
